# Fonts
font_family Fira Code
italic_font Fira Code Italic
font_size 14

# Cursor and ligatures
cursor_trail 10
cursor_trail_start_threshold 0
shell_integration no-cursor
cursor_trail_decay 0.01 0.15
cursor_shape block
cursor_blink true
disable_ligatures never

# Window
initial_window_width 900
initial_window_height 555
remember_window_size yes
scrollback_lines 10000

# hide title bar
hide_window_decorations titlebar-only


# Misc
term xterm-256color
dynamic_background_opacity yes
background_opacity 0.9
copy_on_select yes

# Keybindings
macos_option_as_alt both
map Cmd+a send_key Ctrl+a
map Cmd+z send_key Ctrl+z
map alt+s send_key alt+s
map alt+c send_key alt+c
map alt+x send_key alt+x
map Cmd+r send_key Ctrl+r
map Cmd+e send_key Ctrl+e
map Cmd+c send_key Ctrl+c
map Cmd+f send_key Ctrl+f
map alt+e set_tab_title

map super+u           set_background_opacity 1
map super+shift+u     set_background_opacity default
map super+shift+i     set_background_opacity 0.9

# map super+k launch  ~/.config/kitty/kitty.conf

# map a keybinding to run a kitten command
map alt+t kitten themes

# switching tabs
map shift+right next_tab
map shift+left previous_tab

# Switch focus to the neighboring window in the indicated direction
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

vim:fileencoding=utf-8:foldmethod=marker

tab_bar_style powerline

tab_powerline_style round

# BEGIN_KITTY_THEME
Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
