sock: /Users/tariq/.local/share/telebit/var/run/telebit.sock
root: /Users/tariq/Applications/telebit
community_member: true
telemetry: true
newsletter: false
ssh_auto: 22
servernames:
  light-wolverine-59.telebit.io:
    wildcard: true
    handler: 8888
ports: {}
email: liwof26574@evnft.com
agree_tos: true
relay: telebit.cloud
token: >-
  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk0M2JiYTU0ODQwZDA4NmIxOGJkNTUxNiIsImlhdCI6MTczNTg1OTk2Miwic3ViIjoibGl3b2YyNjU3NEBldm5mdC5jb20iLCJpc3MiOiJ0ZWxlYml0LmNsb3VkIiwiYXVkIjoidGVsZWJpdC5jbG91ZCIsImRvbWFpbnMiOlsibGlnaHQtd29sdmVyaW5lLTU5LnRlbGViaXQuaW8iXSwicG9ydHMiOlsxOTEwMV19.hpP9eN-Ud5hJA7EXXv-nqQNhGKTUDso-gqtoyG931Oc
secret: null
