vim.pack.add({ "https://github.com/nvim-mini/mini.nvim" })
require("mini.surround").setup({})
require("mini.cmdline").setup({})
require("mini.icons").setup({})
require("mini.completion").setup({})
require("mini.snippets").setup({})
require("mini.pick").setup({})
require("mini.statusline").setup({})
require("mini.tabline").setup({})
require("mini.notify").setup({})
require("mini.starter").setup({})
