"use strict";var C=Object.create;var m=Object.defineProperty;var I=Object.getOwnPropertyDescriptor;var O=Object.getOwnPropertyNames;var L=Object.getPrototypeOf,D=Object.prototype.hasOwnProperty;var M=(e,r)=>{for(var t in r)m(e,t,{get:r[t],enumerable:!0})},v=(e,r,t,c)=>{if(r&&typeof r=="object"||typeof r=="function")for(let s of O(r))!D.call(e,s)&&s!==t&&m(e,s,{get:()=>r[s],enumerable:!(c=I(r,s))||c.enumerable});return e};var y=(e,r,t)=>(t=e!=null?C(L(e)):{},v(r||!e||!e.__esModule?m(t,"default",{value:e,enumerable:!0}):t,e)),W=e=>v(m({},"__esModule",{value:!0}),e);var z={};M(z,{default:()=>_});module.exports=W(z);var a=require("@raycast/api");var h=require("@raycast/api");var u=y(require("react")),n=require("@raycast/api");var f=y(require("node:fs")),b=y(require("node:path"));var E=require("react/jsx-runtime");function g(e,r){let t=e instanceof Error?e.message:String(e);return(0,n.showToast)({style:n.Toast.Style.Failure,title:r?.title??"Something went wrong",message:r?.message??t,primaryAction:r?.primaryAction??S(e),secondaryAction:r?.primaryAction?S(e):void 0})}var S=e=>{let r=!0,t="[Extension Name]...",c="";try{let o=JSON.parse((0,f.readFileSync)((0,b.join)(n.environment.assetsPath,"..","package.json"),"utf8"));t=`[${o.title}]...`,c=`https://raycast.com/${o.owner||o.author}/${o.name}`,(!o.owner||o.access==="public")&&(r=!1)}catch{}let s=n.environment.isDevelopment||r,$=e instanceof Error?e?.stack||e?.message||"":String(e);return{title:s?"Copy Logs":"Report Error",onAction(o){o.hide(),s?n.Clipboard.copy($):(0,n.open)(`https://github.com/raycast/extensions/issues/new?&labels=extension%2Cbug&template=extension_bug_report.yml&title=${encodeURIComponent(t)}&extension-url=${encodeURI(c)}&description=${encodeURIComponent(`#### Error:
\`\`\`
${$}
\`\`\`
`)}`)}}};var p=require("react");function A(){let[e,r]=(0,p.useState)([]),[t,c]=(0,p.useState)(!0);(0,p.useEffect)(()=>{s()},[]);let s=async()=>{try{c(!0);let i=await h.LocalStorage.getItem("gemini_command_history");i&&r(JSON.parse(i)),c(!1)}catch(i){g(i),console.error("Failed to load command history:",i),c(!1)}};return{history:e,isLoading:t,addToHistory:async(i,R,T)=>{try{let d=await h.LocalStorage.getItem("gemini_command_history"),w=d?JSON.parse(d):[],P={id:Date.now(),timestamp:new Date().toISOString(),prompt:i,response:R,model:T},U=new Date(Date.now()-1e3).toISOString();if(w.some(x=>x.prompt===i&&x.timestamp>U))return;let k=[P,...w];await h.LocalStorage.setItem("gemini_command_history",JSON.stringify(k)),r(k)}catch(d){g(d),console.error("Failed to add to command history:",d)}},clearHistory:async()=>{try{r([]),await h.LocalStorage.removeItem("gemini_command_history")}catch(i){g(i),console.error("Failed to clear command history:",i)}},loadHistory:s}}var l=require("react/jsx-runtime");function _(){let{history:e,clearHistory:r}=A();return(0,l.jsx)(a.List,{isShowingDetail:!0,children:e.map(t=>(0,l.jsx)(a.List.Item,{title:t.prompt.length>60?t.prompt.substring(0,60)+"...":t.prompt,subtitle:new Date(t.timestamp).toLocaleString(),accessories:[{text:t.model?`Model: ${t.model}`:"Model: Not specified",tooltip:"Model used for this query"}],detail:(0,l.jsx)(a.List.Item.Detail,{markdown:`## Prompt

${t.prompt}

---

## Response

${t.response}

---

**Time**: ${new Date(t.timestamp).toLocaleString()}
**Model**: ${t.model||"Not specified"}`}),actions:(0,l.jsxs)(a.ActionPanel,{children:[(0,l.jsx)(a.Action.CopyToClipboard,{title:"Copy Response",content:t.response,shortcut:{modifiers:["cmd"],key:"c"}}),(0,l.jsx)(a.Action.CopyToClipboard,{title:"Copy Prompt",content:t.prompt,shortcut:{modifiers:["cmd","shift"],key:"c"}}),(0,l.jsx)(a.Action,{title:"Clear History",icon:a.Icon.Trash,shortcut:{modifiers:["shift","cmd"],key:"backspace"},onAction:async()=>{await(0,a.confirmAlert)({title:"Are you sure?"})&&r()}})]})},t.id))})}
